import Vue from 'vue';
import TextFieldList from './Plans/List/TextField';
import TextAreaList from './Plans/List/TextArea';
import BoolList from './Plans/List/Bool';
import DateTimeList from './Plans/List/DateTime';
import PlanFormField from './Plans/PlanFormField';
import TextField from './Plans/Form/TextField';
import TextArea from './Plans/Form/TextArea';
import Bool from './Plans/Form/Bool';
import Group from './Plans/Form/Group';
import LabelList from './Plans/List/Label';
import Select from './Plans/Form/Select';
import Lookup from './Plans/Form/Lookup';
import Switcher from './Plans/Form/Switcher';
import OrderingList from './Plans/List/Ordering';
import Button from './Plans/List/Button';
import DateTimeForm from './Plans/Form/DateTime';
import SelectList from './Plans/List/Select';
import Password from './Plans/Form/Password';
import BulkVariantGroup from './Plans/Form/BulkVariantGroup';

Vue.component('BoolList', BoolList);
Vue.component('ButtonList', Button);
Vue.component('DateTimeList', DateTimeList);
Vue.component('LabelList', LabelList);
Vue.component('OrderingList', OrderingList);
Vue.component('SelectList', SelectList);
Vue.component('TextAreaList', TextAreaList);
Vue.component('TextFieldList', TextFieldList);

Vue.component('PlanFormField', PlanFormField);

Vue.component('BoolForm', Bool);
Vue.component('BulkVariantGroupForm', BulkVariantGroup);
Vue.component('DateTimeForm', DateTimeForm);
Vue.component('GroupForm', Group);
Vue.component('LookupForm', Lookup);
Vue.component('PasswordForm', Password);
Vue.component('SelectForm', Select);
Vue.component('SwitcherForm', Switcher);
Vue.component('TextAreaForm', TextArea);
Vue.component('TextFieldForm', TextField);
